// Mock data for QPR Portal Dashboard and Workflow Testing

export const mockSuppliers = [
  {
    id: 1,
    vendorCode: "31012100",
    vendorName: "PT TEMARU ENGINEERING INDONESIA",
    status: "Aktif",
    address: "Kawasan Industri MM2100, Cikarang Barat, Bekasi",
    contactPerson: "Bpk. Budi Santoso",
    phone: "021-8980123",
    email: "qa@temaru.co.id",
  },
  {
    id: 2,
    vendorCode: "31012200",
    vendorName: "PT ASTRA OTOPARTS TBK",
    status: "Aktif",
    address: "Jl. Raya Pegangsaan Dua Km. 2.2, Kelapa Gading, Jakarta Utara",
    contactPerson: "Ibu Maya Dewi",
    phone: "021-4603550",
    email: "commercial@aop.co.id",
  },
  {
    id: 3,
    vendorCode: "31012300",
    vendorName: "PT TOYOTA BOSHOKU INDONESIA",
    status: "Aktif",
    address: "Kawasan Industri MM2100 Blok J-9, Cikarang Barat, Bekasi",
    contactPerson: "Bpk. Hendra Gunawan",
    phone: "021-8980777",
    email: "purchasing@tbina.toyota-boshoku.com",
  },
];

export const mockParts = [
  {
    id: 1,
    partNumber: "IT-650",
    partName: "INNER TUBE,650 A",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    allowanceRatio: 0.5,
    unitPrice: 85000,
    status: "UNDER ALLOWANCE",
    hasNcrActive: false,
  },
  {
    id: 2,
    partNumber: "PIN-880",
    partName: "PIN PIVOT 880 B",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    allowanceRatio: 0.5,
    unitPrice: 42500,
    status: "UNDER ALLOWANCE",
    hasNcrActive: false,
  },
  {
    id: 3,
    partNumber: "BRK-102",
    partName: "BRACKET FORGING 102",
    supplierId: 2,
    supplierName: "PT ASTRA OTOPARTS TBK",
    allowanceRatio: 0.8,
    unitPrice: 125000,
    status: "UNDER ALLOWANCE",
    hasNcrActive: false,
  },
  {
    id: 4,
    partNumber: "GL-001",
    partName: "GUIDE LEVER 001",
    supplierId: 3,
    supplierName: "PT TOYOTA BOSHOKU INDONESIA",
    allowanceRatio: 0.5,
    unitPrice: 65000,
    status: "UNDER ALLOWANCE",
    hasNcrActive: false,
  },
];

export const mockDeliveries = {
  1: [
    { date: "2026-09-01", qty: 1000, ng: 30, lotNo: "LOT-0901-A" },
    { date: "2026-09-02", qty: 1200, ng: 45, lotNo: "LOT-0902-B" },
  ],
  2: [
    { date: "2026-09-03", qty: 2000, ng: 60, lotNo: "LOT-0903-C" },
  ],
};

export const mockNotifications = [
  {
    id: 1,
    title: "QPR Baru Menunggu Approval Section Head",
    message: "Dokumen 01/QI/QPR/SUB/09/26 telah diterbitkan oleh Foreman Hendrik S.",
    time: "10 menit yang lalu",
    unread: true,
  },
  {
    id: 2,
    title: "Otorisasi Purchasing QPR Diperlukan",
    message: "Dokumen 04/QI/QPR/SUB/09/26 telah disetujui Div Head, siap di-approve Purchasing.",
    time: "1 jam yang lalu",
    unread: true,
  },
];

export const mockAllowanceHistory = [
  {
    id: 1,
    partNumber: "IT-650",
    oldAllowance: 0.6,
    newAllowance: 0.5,
    changedBy: "Septian Nugraha",
    date: "2026-08-15",
    reason: "Review efisiensi proses machining supplier Q3",
  },
];

export const mockPendingNcrs = [
  {
    id: 1,
    ncrNumber: "NCR/2026/09/001",
    date: "2026-09-01",
    partId: 1,
    partNumber: "IT-650",
    partName: "INNER TUBE,650 A",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    qtyNg: 30,
    defectType: "Scratch & Burr Outer Dia",
    disposition: "QPR Claim",
    status: "WAITING_APPROVAL",
    requiredRole: "Section Head",
  },
];

// Mock QPR records designed to test every stage of the 4-level sequential approval workflow
export const mockPendingQprs = [
  // Stage 1: Waiting for Section Head Approval (Login: 2301 Septian Nugraha)
  {
    id: 1,
    qprNumber: "01/QI/QPR/SUB/09/26",
    date: "2026-09-01",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    vendorCode: "31012100",
    partId: 1,
    partNumber: "IT-650",
    partName: "INNER TUBE,650 A",
    refNcrNumber: "NCR/2026/09/001",
    problem: "Defect visual scratch & burr pada outer diameter komponen Inner Tube.",
    claimType: "MATERIAL, PROSES M/C",
    totalQty: 1000,
    totalQtyNg: 30,
    totalStdAllowance: 5,
    billableQty: 25,
    unitPrice: 85000,
    claimAmount: "Rp 2.125.000",
    status: "WAITING_APPROVAL",
    requiredRole: "Section Head",
    createdPeriod: "09/26",
    creatorName: "Hendrik S.",
    creatorNpk: "0890",
    progress: {},
  },
  // Stage 2: Waiting for Dept Head Approval (Login: 2301 Septian Nugraha)
  {
    id: 2,
    qprNumber: "02/QI/QPR/SUB/09/26",
    date: "2026-09-02",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    vendorCode: "31012100",
    partId: 1,
    partNumber: "IT-650",
    partName: "INNER TUBE,650 A",
    refNcrNumber: "NCR/2026/09/002",
    problem: "Porous defect pada casting bracket melebihi spesifikasi standar QA.",
    claimType: "MATERIAL, PROSES CHECK",
    totalQty: 1200,
    totalQtyNg: 45,
    totalStdAllowance: 6,
    billableQty: 39,
    unitPrice: 85000,
    claimAmount: "Rp 3.315.000",
    status: "WAITING_APPROVAL",
    requiredRole: "Dept Head",
    createdPeriod: "09/26",
    creatorName: "Hendrik S.",
    creatorNpk: "0890",
    progress: {
      checksumSectionHead: "APPROVED_BY_SECTION_HEAD_1788700100",
      remarksSectionHead: "Inspeksi sampling lot 09-B menunjukkan 45 pcs NG.",
      approvedAtSectionHead: "2026-09-02T09:00:00Z",
    },
  },
  // Stage 3: Waiting for Div Head Approval (Login: 1335 Putu Ratna Saputra)
  {
    id: 3,
    qprNumber: "03/QI/QPR/SUB/09/26",
    date: "2026-09-03",
    supplierId: 2,
    supplierName: "PT ASTRA OTOPARTS TBK",
    vendorCode: "31012200",
    partId: 3,
    partNumber: "BRK-102",
    partName: "BRACKET FORGING 102",
    refNcrNumber: "NCR/2026/09/003",
    problem: "Ketidaksesuaian dimensi pin poros melebihi batas toleransi drawing QA.",
    claimType: "PROSES M/C, HEAT TREATMENT",
    totalQty: 2000,
    totalQtyNg: 60,
    totalStdAllowance: 10,
    billableQty: 50,
    unitPrice: 125000,
    claimAmount: "Rp 6.250.000",
    status: "WAITING_APPROVAL",
    requiredRole: "Div Head",
    createdPeriod: "09/26",
    creatorName: "Deny Maulana",
    creatorNpk: "3079",
    progress: {
      checksumSectionHead: "APPROVED_BY_SECTION_HEAD_1788700200",
      remarksSectionHead: "Disetujui Section Head.",
      approvedAtSectionHead: "2026-09-03T08:30:00Z",
      checksumDeptHead: "APPROVED_BY_DEPT_HEAD_1788700250",
      remarksDeptHead: "Disetujui Dept Head, mohon persetujuan Div Head.",
      approvedAtDeptHead: "2026-09-03T10:00:00Z",
    },
  },
  // Stage 4: Waiting for Purchasing Approval (Login: 1175 Irvan H. N. / 3790 Cicik Andria)
  {
    id: 4,
    qprNumber: "04/QI/QPR/SUB/09/26",
    date: "2026-09-04",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    vendorCode: "31012100",
    partId: 1,
    partNumber: "IT-650",
    partName: "INNER TUBE,650 A",
    refNcrNumber: "NCR/2026/09/004",
    problem: "Karat / korosi pada permukaan coating setelah uji salt spray 48 jam.",
    claimType: "PAINTING/PLATING",
    totalQty: 1500,
    totalQtyNg: 50,
    totalStdAllowance: 7,
    billableQty: 43,
    unitPrice: 85000,
    claimAmount: "Rp 3.655.000",
    status: "WAITING_APPROVAL",
    requiredRole: "Purchasing",
    createdPeriod: "09/26",
    creatorName: "Hendrik S.",
    creatorNpk: "0890",
    progress: {
      checksumSectionHead: "APPROVED_BY_SECTION_HEAD_1788700300",
      remarksSectionHead: "Disetujui Section Head.",
      approvedAtSectionHead: "2026-09-04T08:30:00Z",
      checksumDeptHead: "APPROVED_BY_DEPT_HEAD_1788700350",
      remarksDeptHead: "Disetujui Dept Head.",
      approvedAtDeptHead: "2026-09-04T10:00:00Z",
      checksumDivHead: "APPROVED_BY_DIV_HEAD_1788700400",
      remarksDivHead: "Disetujui Div Head. Lanjutkan otorisasi Purchasing dan terbitkan CL.",
      approvedAtDivHead: "2026-09-04T13:30:00Z",
    },
  },
  // Stage 5: Full Approved by Purchasing -> Ready to Create Confirmation Letter / Buat CL
  {
    id: 5,
    qprNumber: "05/QI/QPR/SUB/09/26",
    date: "2026-09-05",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    vendorCode: "31012100",
    partId: 1,
    partNumber: "IT-650",
    partName: "INNER TUBE,650 A",
    refNcrNumber: "NCR/2026/09/005",
    problem: "Dimensi ulang finish grind out of spec pada batch 09-E.",
    claimType: "PROSES M/C",
    totalQty: 2500,
    totalQtyNg: 80,
    totalStdAllowance: 12,
    billableQty: 68,
    unitPrice: 85000,
    claimAmount: "Rp 5.780.000",
    status: "APPROVED",
    requiredRole: "Purchasing",
    createdPeriod: "09/26",
    creatorName: "Hendrik S.",
    creatorNpk: "0890",
    progress: {
      checksumSectionHead: "APPROVED_BY_SECTION_HEAD_1788700500",
      remarksSectionHead: "Disetujui Section Head.",
      approvedAtSectionHead: "2026-09-05T08:30:00Z",
      checksumDeptHead: "APPROVED_BY_DEPT_HEAD_1788700550",
      remarksDeptHead: "Disetujui Dept Head.",
      approvedAtDeptHead: "2026-09-05T10:00:00Z",
      checksumDivHead: "APPROVED_BY_DIV_HEAD_1788700600",
      remarksDivHead: "Approved Div Head.",
      approvedAtDivHead: "2026-09-05T11:30:00Z",
      checksumPurchasing: "APPROVED_BY_PURCHASING_1788700650",
      remarksPurchasing: "Disetujui Purchasing. Dokumen siap diterbitkan Confirmation Letter.",
      approvedAtPurchasing: "2026-09-05T14:00:00Z",
    },
  },
];

// Mock Confirmation Letters (CL) across various processing stages with attached QPR data
export const mockConfirmationLetters = [
  // CL 1: Menunggu Approval Dept Accounting (Login: 3123 Anindita) - dengan QPR attachment 05/QI/QPR/SUB/09/26
  {
    id: 1,
    clNumber: "CL/MTM/2026/09/001",
    dateSent: "2026-09-06",
    qprNumber: "05/QI/QPR/SUB/09/26",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    vendorName: "PT TEMARU ENGINEERING INDONESIA",
    vendorCode: "31012100",
    amount: "Rp 1.144.283",
    status: "PENDING",
    deptAccountingApproved: false,
    purchasingSentCl: false,
    vendorApproved: false,
    items: [
      {
        partId: 1,
        partNumber: "HC-IMV-683N",
        partName: "HUB CLUTCH, IMV 683N",
        description: "HUB CLUTCH, IMV 683N",
        totalQty: 1000,
        qtyNg: 14,
        stdAllowance: 0,
        billableQty: 14,
        unitPrice: 49516,
        taxRate: 0.11,
        amount: 693224,
      },
      {
        partId: 2,
        partNumber: "HC-RZN",
        partName: "HUB CLUTCH, RZN",
        description: "HUB CLUTCH, RZN",
        totalQty: 500,
        qtyNg: 6,
        stdAllowance: 0,
        billableQty: 6,
        unitPrice: 56277,
        taxRate: 0.11,
        amount: 337662,
      },
    ],
    qprAttachment: {
      id: 5,
      qprNumber: "05/QI/QPR/SUB/09/26",
      date: "2026-09-05",
      supplierName: "PT TEMARU ENGINEERING INDONESIA",
      vendorCode: "31012100",
      partNumber: "HC-IMV-683N",
      partName: "HUB CLUTCH, IMV 683N",
      refNcrNumber: "NCR/2026/09/005",
      problem: "Dimensi ulang finish grind out of spec pada komponen Hub Clutch batch 09-E.",
      claimType: ["MATERIAL", "PROSES M/C"],
      totalItems: 1500,
      rejectItems: 20,
      allowanceRatio: 0,
      claimAmount: "Rp 1.144.283",
      status: "APPROVED",
      requiredRole: "Purchasing",
      period: "09/26",
      creatorName: "Hendrik S.",
      creatorNpk: "0890",
      parts: [
        {
          partId: 1,
          partNumber: "HC-IMV-683N",
          partName: "HUB CLUTCH, IMV 683N",
          totalQty: 1000,
          qtyNg: 14,
          stdAllowance: 0,
          qtyClaim: 14,
          unitPrice: 49516,
        },
        {
          partId: 2,
          partNumber: "HC-RZN",
          partName: "HUB CLUTCH, RZN",
          totalQty: 500,
          qtyNg: 6,
          stdAllowance: 0,
          qtyClaim: 6,
          unitPrice: 56277,
        },
      ],
      remarks: "Disetujui Purchasing. Dokumen siap diterbitkan Confirmation Letter.",
      approvalProgress: {
        checksumSectionHead: "APPROVED_BY_SECTION_HEAD_1788700500",
        remarksSectionHead: "Inspeksi sampling lot 09-E menunjukkan 20 pcs reject.",
        approvedAtSectionHead: "2026-09-05T08:30:00Z",
        checksumDeptHead: "APPROVED_BY_DEPT_HEAD_1788700550",
        remarksDeptHead: "Disetujui Dept Head.",
        approvedAtDeptHead: "2026-09-05T10:00:00Z",
        checksumDivHead: "APPROVED_BY_DIV_HEAD_1788700600",
        remarksDivHead: "Approved Div Head.",
        approvedAtDivHead: "2026-09-05T11:30:00Z",
        checksumPurchasing: "APPROVED_BY_PURCHASING_1788700650",
        remarksPurchasing: "Disetujui Purchasing. Siap diterbitkan Confirmation Letter.",
        approvedAtPurchasing: "2026-09-05T14:00:00Z",
      },
    },
  },
  // CL 2: Disetujui Accounting, Siap Dikirim ke Vendor oleh Purchasing (Login: 3790 Cicik)
  {
    id: 2,
    clNumber: "CL/MTM/2026/09/002",
    dateSent: "2026-09-05",
    qprNumber: "03/QI/QPR/SUB/09/26",
    supplierId: 2,
    supplierName: "PT ASTRA OTOPARTS TBK",
    vendorName: "PT ASTRA OTOPARTS TBK",
    vendorCode: "31012200",
    amount: "Rp 6.250.000",
    status: "PENDING",
    deptAccountingApproved: true,
    deptAccountingApprovedAt: "2026-09-06T10:00:00Z",
    purchasingSentCl: false,
    vendorApproved: false,
    items: [
      {
        partId: 3,
        partNumber: "BRK-102",
        partName: "BRACKET FORGING 102",
        description: "BRACKET FORGING 102",
        totalQty: 2000,
        qtyNg: 60,
        stdAllowance: 10,
        billableQty: 50,
        unitPrice: 125000,
        taxRate: 0.11,
        amount: 6250000,
      },
    ],
    qprAttachment: {
      id: 3,
      qprNumber: "03/QI/QPR/SUB/09/26",
      date: "2026-09-03",
      supplierName: "PT ASTRA OTOPARTS TBK",
      vendorCode: "31012200",
      partNumber: "BRK-102",
      partName: "BRACKET FORGING 102",
      refNcrNumber: "NCR/2026/09/003",
      problem: "Ketidaksesuaian dimensi pin poros melebihi batas toleransi drawing QA.",
      claimType: ["PROSES M/C", "HEAT TREATMENT"],
      totalItems: 2000,
      rejectItems: 60,
      allowanceRatio: 0.5,
      claimAmount: "Rp 6.250.000",
      status: "APPROVED",
      requiredRole: "Purchasing",
      period: "09/26",
      creatorName: "Deny Maulana",
      creatorNpk: "3079",
      parts: [
        {
          partId: 3,
          partNumber: "BRK-102",
          partName: "BRACKET FORGING 102",
          totalQty: 2000,
          qtyNg: 60,
          stdAllowance: 10,
          qtyClaim: 50,
          unitPrice: 125000,
        },
      ],
      remarks: "Disetujui Div Head. Lanjutkan otorisasi Purchasing dan terbitkan CL.",
      approvalProgress: {
        checksumSectionHead: "APPROVED_BY_SECTION_HEAD_1788700200",
        remarksSectionHead: "Disetujui Section Head.",
        checksumDeptHead: "APPROVED_BY_DEPT_HEAD_1788700250",
        remarksDeptHead: "Disetujui Dept Head.",
        checksumDivHead: "APPROVED_BY_DIV_HEAD_1788700400",
        remarksDivHead: "Disetujui Div Head.",
        checksumPurchasing: "APPROVED_BY_PURCHASING_1788700600",
        remarksPurchasing: "Disetujui Purchasing.",
      },
    },
  },
  // CL 3: Disetujui Vendor, Siap Proses SSC Billing & Payment (Login: 3616 Bagas)
  {
    id: 3,
    clNumber: "CL/MTM/2026/09/003",
    dateSent: "2026-09-04",
    qprNumber: "02/QI/QPR/SUB/09/26",
    supplierId: 1,
    supplierName: "PT TEMARU ENGINEERING INDONESIA",
    vendorName: "PT TEMARU ENGINEERING INDONESIA",
    vendorCode: "31012100",
    amount: "Rp 3.315.000",
    status: "APPROVED_BY_VENDOR",
    deptAccountingApproved: true,
    deptAccountingApprovedAt: "2026-09-04T11:00:00Z",
    purchasingSentCl: true,
    purchasingSentClAt: "2026-09-04T14:00:00Z",
    vendorApproved: true,
    vendorApprovedAt: "2026-09-05T09:00:00Z",
    items: [
      {
        partId: 1,
        partNumber: "IT-650",
        partName: "INNER TUBE,650 A",
        description: "INNER TUBE,650 A",
        totalQty: 1200,
        qtyNg: 45,
        stdAllowance: 6,
        billableQty: 39,
        unitPrice: 85000,
        taxRate: 0.11,
        amount: 3315000,
      },
    ],
    qprAttachment: {
      id: 2,
      qprNumber: "02/QI/QPR/SUB/09/26",
      date: "2026-09-02",
      supplierName: "PT TEMARU ENGINEERING INDONESIA",
      vendorCode: "31012100",
      partNumber: "IT-650",
      partName: "INNER TUBE,650 A",
      refNcrNumber: "NCR/2026/09/002",
      problem: "Porous defect pada casting bracket melebihi spesifikasi standar QA.",
      claimType: ["MATERIAL", "PROSES CHECK"],
      totalItems: 1200,
      rejectItems: 45,
      allowanceRatio: 0.5,
      claimAmount: "Rp 3.315.000",
      status: "APPROVED",
      requiredRole: "Purchasing",
      period: "09/26",
      creatorName: "Hendrik S.",
      creatorNpk: "0890",
      parts: [
        {
          partId: 1,
          partNumber: "IT-650",
          partName: "INNER TUBE,650 A",
          totalQty: 1200,
          qtyNg: 45,
          stdAllowance: 6,
          qtyClaim: 39,
          unitPrice: 85000,
        },
      ],
      remarks: "Inspeksi sampling lot 09-B menunjukkan 45 pcs NG.",
      approvalProgress: {
        checksumSectionHead: "APPROVED_BY_SECTION_HEAD_1788700100",
        remarksSectionHead: "Inspeksi sampling lot 09-B menunjukkan 45 pcs NG.",
        checksumDeptHead: "APPROVED_BY_DEPT_HEAD_1788700250",
        remarksDeptHead: "Disetujui Dept Head.",
        checksumDivHead: "APPROVED_BY_DIV_HEAD_1788700300",
        remarksDivHead: "Disetujui Div Head.",
        checksumPurchasing: "APPROVED_BY_PURCHASING_1788700350",
        remarksPurchasing: "Disetujui Purchasing.",
      },
    },
  },
];

// Mock Users for role testing
export const mockTestUsers = [
  { npk: "999", name: "Administrator", role: "System Administrator", code: "admin", access: "Semua Menu" },
  { npk: "0890", name: "Hendrik S.", role: "QA/QC Operator (Foreman)", code: "foreman", access: "Buat QPR, Draft QPR, List QPR & CL" },
  { npk: "3079", name: "Deny Maulana", role: "QA/QC Operator (Foreman)", code: "foreman", access: "Buat QPR, Draft QPR, List QPR & CL" },
  { npk: "2301", name: "Septian Nugraha", role: "QA Section Head & Dept Head", code: "sect_dept_head", access: "Approval QPR (Sec Head & Dept Head), Dashboard, List QPR & CL" },
  { npk: "1335", name: "Putu Ratna Saputra", role: "QA Division Head", code: "div_head", access: "Approval QPR (Div Head), Dashboard, List QPR & CL" },
  { npk: "1175", name: "Irvan H. N.", role: "Purchasing Approval QPR", code: "purchasing_qpr", access: "Approval QPR (Khusus Purchasing), Dashboard, List QPR & CL" },
  { npk: "3790", name: "Cicik Andria", role: "Purchasing Departemen", code: "purchasing", access: "Buat CL, Approval CL (Kirim Vendor), Dashboard, List QPR & CL" },
  { npk: "3123", name: "Anindita Irnilaningtyas", role: "Dept Accounting", code: "accounting", access: "Approval Confirmation Letter (CL), Dashboard, List QPR & CL" },
  { npk: "3616", name: "Bagas Nur Pratama", role: "Finance Accounting", code: "finance", access: "SSC Billing, SSC Payment (I-Memo), Dashboard, List QPR & CL" },
];
